// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSq2o1nRu3ao4VSeKYIz3sfm9mrHfZWEk',
    appId: '1:55776588459:web:433c30b37ab55187533dee',
    messagingSenderId: '55776588459',
    projectId: 'gwele-33e7f',
    authDomain: 'gwele-33e7f.firebaseapp.com',
    storageBucket: 'gwele-33e7f.appspot.com',
    measurementId: 'G-Y8R1PJ52FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9t1ghW8clQRiAsKeL45MHDe7C0U0CvGo',
    appId: '1:55776588459:android:11396c54f32c33e4533dee',
    messagingSenderId: '55776588459',
    projectId: 'gwele-33e7f',
    storageBucket: 'gwele-33e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLtuBrQohWj6fuoITvI8YF0nHo8kIjytU',
    appId: '1:55776588459:ios:e49072e1891228b0533dee',
    messagingSenderId: '55776588459',
    projectId: 'gwele-33e7f',
    storageBucket: 'gwele-33e7f.appspot.com',
    iosBundleId: 'com.odk.gwele',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLtuBrQohWj6fuoITvI8YF0nHo8kIjytU',
    appId: '1:55776588459:ios:e49072e1891228b0533dee',
    messagingSenderId: '55776588459',
    projectId: 'gwele-33e7f',
    storageBucket: 'gwele-33e7f.appspot.com',
    iosBundleId: 'com.odk.gwele',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSq2o1nRu3ao4VSeKYIz3sfm9mrHfZWEk',
    appId: '1:55776588459:web:7863d4685b115eef533dee',
    messagingSenderId: '55776588459',
    projectId: 'gwele-33e7f',
    authDomain: 'gwele-33e7f.firebaseapp.com',
    storageBucket: 'gwele-33e7f.appspot.com',
    measurementId: 'G-QFBNS7DEJB',
  );
}
